In [61]:
import numpy as np

In [62]:
a = np.array([1, 2, 3, 4, 5, 7, 10])
b = np.array([1, 2, 3, 4, 5, 7, 10])

Vector Operations

In [63]:
a * b

array([  1,   4,   9,  16,  25,  49, 100])

In [64]:
a * 8

array([ 8, 16, 24, 32, 40, 56, 80])

In [65]:
b - 2

array([-1,  0,  1,  2,  3,  5,  8])

In [66]:
a / 44

array([0.02272727, 0.04545455, 0.06818182, 0.09090909, 0.11363636,
       0.15909091, 0.22727273])

Vector - vector multiplication

In [67]:
def vector_vector_multiplicaiton(u, v):
    assert u.shape[0] == v.shape[0]
    n = u.shape[0]
    result = 0
    for i in range(n):
        result = result + u[i] * v[i]

    return result


In [68]:
vector_vector_multiplicaiton(a, b)

204

In [69]:
a.dot(b)

204

Matrix-vector multiplication

In [70]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    num_rows = U.shape[0]
    result = np.zeros(num_rows)
    for i in range(num_rows):
        result[i] = vector_vector_multiplicaiton(U[i], v)

    return result

In [73]:
U = np.array([[2, 4, 5, 6], [1, 2, 1, 2], [3, 1, 2, 1]])
v = np.array([1, 0.5, 2, 1])
matrix_vector_multiplication(U, v)

array([20. ,  6. ,  8.5])

In [72]:
np.array([[1, 2, 3], [4, 5, 6]]).dot(np.array([1, 2, 3]))

array([14, 32])

Matrix matrix multiplication

In [74]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 1]
])

In [75]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    result = np.zeros((num_rows, num_cols))
    for i in range(num_cols):
        v = V[:, i]
        result[:, i] = matrix_vector_multiplication(U, v)

    return result

In [76]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 19. ],
       [ 5. ,  6. ,  7. ],
       [ 5. ,  8.5, 10. ]])

In [77]:
U.dot(V)

array([[14. , 20. , 19. ],
       [ 5. ,  6. ,  7. ],
       [ 5. ,  8.5, 10. ]])

Identity Matrix

In [79]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [80]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 1. ]])

In [83]:
I = np.eye(3)

In [84]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 1. ]])

In [85]:
Vs = V[[0, 1, 2]]

In [86]:
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [92]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [91]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])