In [1]:
import numpy as np

Creating arrays

In [3]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2.3)

array([2.3, 2.3, 2.3, 2.3, 2.3, 2.3, 2.3, 2.3, 2.3, 2.3])

In [8]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [12]:
a[3] = 9
a

array([1, 2, 3, 9, 5])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [17]:
np.linspace(0, 0.5, 11)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ])

Multi-dimentional arrays

In [18]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
n = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [21]:
n[0, 0]

1

In [22]:
n[0, 2]

3

In [23]:
n[1]

array([4, 5, 6])

In [24]:
n[2] = [10, 11, 12]

In [25]:
n

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12]])

In [27]:
n[:, 0]

array([ 1,  4, 10])

Randomly generated arrays

In [43]:
np.random.seed(2)
b = np.random.rand(10, 3)

In [34]:
np.random.seed(2)
np.random.randn(10, 3)

array([[-0.41675785, -0.05626683, -2.1361961 ],
       [ 1.64027081, -1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809, -1.05795222],
       [-0.90900761,  0.55145404,  2.29220801],
       [ 0.04153939, -1.11792545,  0.53905832],
       [-0.5961597 , -0.0191305 ,  1.17500122],
       [-0.74787095,  0.00902525, -0.87810789],
       [-0.15643417,  0.25657045, -0.98877905],
       [-0.33882197, -0.23618403, -0.63765501],
       [-1.18761229, -1.42121723, -0.1534952 ]])

In [44]:
np.random.seed(2)
c = np.random.randint(low=0, high=100, size=(10, 3))

In [47]:
b / c

array([[0.01089987, 0.00172842, 0.0076342 ],
       [0.01978738, 0.009776  , 0.00402847],
       [0.00272865, 0.08846728, 0.00881337],
       [0.00544545, 0.00653825, 0.00705523],
       [0.00158329, 0.01092719, 0.00292762],
       [0.02533339, 0.00948861, 0.02471184],
       [0.02288004, 0.00204219, 0.00754099],
       [0.01632163, 0.01019339, 0.00189276],
       [0.00334632, 0.01808319, 0.00389676],
       [0.0015962 , 0.00319284, 0.0039753 ]])

Comparison operations

In [48]:
a >= 2

array([False,  True,  True,  True,  True])

In [49]:
b > 0.5

array([[False, False,  True],
       [False, False, False],
       [False,  True, False],
       [False,  True,  True],
       [False,  True, False],
       [ True,  True, False],
       [ True, False,  True],
       [False, False, False],
       [False,  True, False],
       [False, False, False]])

In [50]:
b[b > 0.5]

array([0.54966248, 0.61927097, 0.62113383, 0.52914209, 0.51357812,
       0.78533515, 0.85397529, 0.84656149, 0.50524609, 0.59674531])

In [51]:
c > b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Summarizing operations

In [53]:
a.min()

1

In [54]:
a.mean()

4.0

In [55]:
a.max()

9

In [58]:
a.sum()

20

In [59]:
c.min(axis=0)

array([ 4,  7, 20])

In [60]:
c.sum(axis=1)

array([127, 147, 116, 219, 195, 141, 143,  97, 129, 224])